### ISSUE TITLE
Code highlighting please!

### ISSUE THREAD

**Issue by igrigorik** [mojombo/github-flavored-markdown#15]
Not an issue, but a feature request... We share code all the time in pages, readme's tickets, etc. Having native code highlighting would be very, very useful!

**Comment by gf3** [comment]
+1 Highlighting would be very helpful.

**Comment by nddrylliog** [comment]
+1 Maybe something similar to: http://www.martin-geber.com/thought/2007/10/27/markdown-syntax-highlighting-django/

**Comment by jena-th** [comment]
+1

**Comment by SoftwareDreamer** [comment]
+1 .. can't imagine how that didn't make it into github.. stackoverflow is a good example for how to do it right

**Comment by keilmillerjr** [comment]
I agree.

**Comment by wamatt** [comment]
+1

**Comment by pgrinchenko** [comment]
+1

**Comment by skeggse** [comment]
@igrigorik as this has been added (see below), could you close the issue, please?

``` cpp
#include <iostream>
using namespace std;

int main ()
{
  cout << "Code highlighting works!";
  return 0;
}
```

**Comment by igrigorik** [comment]
great stuff - thanks!
