### ISSUE TITLE
"Preview post/comment" button, please?

### ISSUE THREAD

**Issue by Drugoy** [mojombo/github-flavored-markdown#18]
I don't get how to use all the tags that github supports. You have very poor documentation of how to use GitHub Flavored Markdown: I don't even know how to paste a link (not as plain text that will be highlighted).
Should I use [url="http://link.here/"]this construction[/url] like on phpbb forums or should I use html syntax and tag "a"?
I wouldn't ask you to write a good documentation, but could you just add "preview post/comment" button, so I could take a look at how my message would look like before I actually send it?

**Comment by chooch** [comment]
what is this

**Comment by Drugoy** [comment]
it's a feature request.
The FAQ is pretty poor, users don't understand the syntax used on github, so why not at least add a "preview" button for posts (currently it appears only for comments)?

**Comment by sr** [comment]
@Drugoy you can hit "m" on any page to get a cheat sheet. Hope that helps. Thanks!

**Comment by chooch** [comment]
cool

**Comment by Drugoy** [comment]
Thanks for that tip, but it's a hidden cheat sheet, so it's useless for the ones who don't know about it.
- once again: there are just written examples without the illustration of what they transform too.
  who the hell knew that if you write some text in square brackets and paste after that a link in rounded brackets - the link gets transformed that way? I didn't until I tried it. I don't want to try every example from there, just to know what they will transform to.
