### ISSUE TITLE
CJK support.

### ISSUE THREAD

**Issue by zhuangya** [mojombo/github-flavored-markdown#19]
I have this wiki page:

https://github.com/bitsmix/dotvim/wiki/Hello

Chinese, Japanese and Korean characters are not show as expected in the code section.

the source code of wiki:

``` javascript
var foo = function(bar) {
    alert('你好'); //"hello" in Chinese.
    alert('こんにちは'); //"hello" in Japanese".
    alert('안녕하세요'); //"hello" in Korean.
};


```
# 

update:

GFM in issue works fine with CJK Characters..  why don't support wiki page?

**Comment by Dither** [comment]
The same thing goes for wikis in other non-ascii languages. Any simple text displays correctly but source code blocks show UTF characters as ISO.

``` javascript
var foo = function(bar) {
    alert('Привет'); // "hello" in Russian.
};
```

Results this:

``` javascript
var foo = function(bar) {
    alert('ÐÑÐ¸Ð²ÐµÑ'); // "hello" in Russian.
};
```

**Comment by skeggse** [comment]
Is this still an issue? If not, could you close the issue?

**Comment by zhuangya** [comment]
it's not a issue anymore now :) cheers.
