### ISSUE TITLE
tables are broken

### ISSUE THREAD

**Issue by panzi** [mojombo/github-flavored-markdown#23]
Tables do no longer work on github. All table related tags except &lt;table&gt; get stripped. See:

<table>
<tr>
<td>Foo</td>
<td>Bar</td>
</tr>
<tr>
<td>Foo</td>
<td>Bar</td>
</tr>
</table>

**Comment by skeggse** [comment]
This appears to be fixed? At least, I see:

``` html
<table>
<tr>
<td>Foo</td>
<td>Bar</td>
</tr>
<tr>
<td>Foo</td>
<td>Bar</td>
</tr>
</table>
```

Were you referring to a `thead` or `tbody` element, or is this fixed?

**Comment by panzi** [comment]
Yes, this issue was fixed some weeks or so after I wrote this bug report.

**Comment by skeggse** [comment]
Great! Could you close the issue, then?
