### ISSUE TITLE
Nested lists have an unwelcome margin-top when parent item not raw text

### ISSUE THREAD

**Issue by aGHz** [mojombo/github-flavored-markdown#25]
For example, this list renders perfectly:
- foo
  - bar
    - baz
    - zoo
  - and so
    - on

But this list does not:
- foo
  - bar, the enclosing UL has a specific margin-top: 0
  - **baz** is bolded
    - margin-top problem here, there is no specific margin-top on the enclosing UL so it inherits a 15px margin

**Comment by skeggse** [comment]
It seems to be fixed, unless I'm misunderstanding the issue. If it is fixed, could you mark the issue as closed?

**Comment by aGHz** [comment]
Indeed, it seems to look good.
