### ISSUE TITLE
bla bla bla test

### ISSUE THREAD

**Issue by abobykin** [mojombo/github-flavored-markdown#30]
<table>
  <tr>
    <th>ID</th><th>Name</th><th>Rank</th>
  </tr>
  <tr>
    <td>1</td><td>Tom Preston-Werner</td><td>Awesome</td>
  </tr>
  <tr>
    <td>2</td><td>Albert Einstein</td><td>Nearly as awesome</td>
  </tr>
</table>

**Comment by Sleashe** [comment]
```
piece_of_code
    test
end
```

**Comment by Sleashe** [comment]
```
test
  test
test
```

**Comment by skeggse** [comment]
@abobykin Could you close this? It isn't actually an issue.
