### ISSUE TITLE
Parenthesis in links don't work

### ISSUE THREAD

**Issue by kzu** [mojombo/github-flavored-markdown#34]
I want to be able to specify links to documentation-style docs, like so:

[GetValue(System.Int32)](Markdown.ApiSite.Api.Sample.GetValue%28System.Int32%29.md)

The link gets all mangled by the parenthesis between the [ ]. It shows up as "GetValue(System.Int32).md)" with the link covering up to the 32, like Markdown.ApiSite.Api.Sample.GetValue(System.Int32

Would be great to have a way to escape the parenthesis. Maybe ` or double parenthesis?

**Comment by kzu** [comment]
Here's an example of a perfectly valid wiki page which can't be linked because of this parentheses issue: https://github.com/danielkzu/MarkdownApiSite/wiki/M-Markdown.ApiSite.Api.Sample.GetValue(System.Int32)

**Comment by dhalperi** [comment]
Looks like this issue is now fixed?

**Comment by kzu** [comment]
yay! :)
