### ISSUE TITLE
URLs with an anchor screw up the generated layout

### ISSUE THREAD

**Issue by BRMatt** [mojombo/github-flavored-markdown#4]
For example,
[Look at this](http://uk2.php.net/manual/en/language.operators.increment.php#77998)

Also [it mucks up linking to lines in files](http://github.com/mojombo/github-flavored-markdown/blob/16c999e8c71134401a78d4d46435517b2271d6ac/sample_content.html#L9)

**Comment by mojombo** [comment]
This is fixed.
