### ISSUE TITLE
Markdown line-break modification a retrograde step

### ISSUE THREAD

**Issue by sroebuck** [mojombo/github-flavored-markdown#5]
I was really pleased to see Markdown support in GitHub, but I'm really disappointed that such a fundamental change has been made as forcing linebreaks on the end of every line.

One of the aims of Markdown is to allow the text files to be easily readable without further rendering.  If you force people to make paragraphs into huge lines then you break this aim for everyone who doesn't work in a auto wordwrap environment.

Stuart.

**Comment by tekkub** [comment]
Your browser doesn't auto-wrap text fields?  We only use GFM for things like issues here, the user's text editor never comes into play.

**Comment by sroebuck** [comment]
What about Readme.md files?

**Comment by tekkub** [comment]
They are not run through GFM, only the standard markdown renderer.  Same goes for md files on Pages.

**Comment by sroebuck** [comment]
To be honest, I've forgot even raising this issue, but it sounds like it's not an issue! :-)

**Comment by tekkub** [comment]
I only noticed it because I came to open a few that users reported on tender :)

**Comment by mojombo** [comment]
Then we're all happy! Well done, everyone.
